### ISSUE TITLE
Wait for page that loaded with ajax

### ISSUE THREAD

**Issue by NetanelBasal** [lapwinglabs/x-ray#138]
There is a way to wait x time for a page to load before making the query?

for example, I want to crawl a website that his content loaded with ajax and I need to wait for the content.

**Comment by sauravskumar99** [comment]
use phantomjs

**Comment by aronduby** [comment]
could you give some more information, or point me in the right direction. I can't seem to find anything with how to actually pull this off.

**Comment by DmitryMaksakov** [comment]
Also can`t find any information about setting the delay after page is loaded and before data reading.

**Comment by gebrits** [comment]
You would use a javascript driver.
See here for a [x-ray driver](https://github.com/phulas/x-ray-nightmare)
using [Nightmare](https://github.com/segmentio/nightmare).

Since I was interested in this as well, I asked specifically if you could
use Nightmare-actions such as **wait**, click, etc. The answer appears to
be [YES](https://github.com/phulas/x-ray-nightmare/issues/3)

**Comment by gebrits** [comment]
You would use a javascript driver.
See here for a [x-ray driver](https://github.com/phulas/x-ray-nightmare)
using [Nightmare](https://github.com/segmentio/nightmare).

Since I was interested in this as well, I asked specifically if you could
use Nightmare-actions such as **wait**, click, etc. The answer appears to
be [YES](phulas/x-ray-nightmare#3)
