### ISSUE TITLE
Cheerio seems more useful

### ISSUE THREAD

**Issue by MMRandy** [lapwinglabs/x-ray#61]
This sure sounded cool, but when it comes to practical use, I find Cheerio to be much more effective (thanks for Cheerio!).  Unless I'm missing something, I don't see a (non-verbose) way to do something at simple as clean a returned string, for example:

```
		x(options.raw, {
			main: '.page-title h1'
		})(function(err, obj) {
			// obj.main = "\n     Scraped String      "
		});
```
With Cheerio, you can simply call .text().trim() on the returned cheerio object.  Is there a way to accomplish the same thing using the collection format above...preferably at the property level rather than in the callback?  Thx

**Comment by matthewmueller** [comment]
Thanks for the feedback. We're still settling on the API. There's actually plans for supporting formatters / filters. In fact it's available in the selector engine, just not x-ray yet:

Selector engine: https://github.com/lapwinglabs/x-ray-select/blob/master/test/strings.js#L39-L40
X-ray: https://github.com/lapwinglabs/x-ray/blob/master/test/index.js#L265-L269

Should be simple to add. Accepting PRs :-). Otherwise we may shift the API around a bit to make it easier to conditionally follow links and do things like formatting.
